version: "3"
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_USER=euchre
      - POSTGRES_PASSWORD=euchre
      - POSTGRES_DB=euchre
    ports:
      - "5001:5432"
  euchre-game:
    build: .
    networks:
      - backend
    volumes:
      - .:/euchre_game
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://euchre:euchre@db:5432/euchre
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: app/__init__.py

networks:
  frontend:
  backend:

volumes:
  db-data:
