version: "3"
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_USER=euchre
      - POSTGRES_PASSWORD=euchre
      - POSTGRES_DB=euchre
  euchre-game: 
    build: .
    networks:
      - backend
    volumes: 
      - .:/euchre_game
    ports: 
      - "5000:5000"
    stdin_open: true
    tty: true

networks:
  frontend: 
  backend:

volumes:
  db-data: 
